/**
 * Autogenerated by Thrift Compiler (0.15.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef CalciteServer_H
#define CalciteServer_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "CalciteServer_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class CalciteServerIf {
 public:
  virtual ~CalciteServerIf() {}
  virtual void ping() = 0;
  virtual void shutdown() = 0;
  virtual void sql2Plan(TPlanResult& _return, const std::string& query, const std::string& schemaName) = 0;
  virtual void updateMetadata(const std::string& catalog, const std::string& table) = 0;
};

class CalciteServerIfFactory {
 public:
  typedef CalciteServerIf Handler;

  virtual ~CalciteServerIfFactory() {}

  virtual CalciteServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(CalciteServerIf* /* handler */) = 0;
  };

class CalciteServerIfSingletonFactory : virtual public CalciteServerIfFactory {
 public:
  CalciteServerIfSingletonFactory(const ::std::shared_ptr<CalciteServerIf>& iface) : iface_(iface) {}
  virtual ~CalciteServerIfSingletonFactory() {}

  virtual CalciteServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(CalciteServerIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<CalciteServerIf> iface_;
};

class CalciteServerNull : virtual public CalciteServerIf {
 public:
  virtual ~CalciteServerNull() {}
  void ping() override {
    return;
  }
  void shutdown() override {
    return;
  }
  void sql2Plan(TPlanResult& /* _return */, const std::string& /* query */, const std::string& /* schemaName */) override {
    return;
  }
  void updateMetadata(const std::string& /* catalog */, const std::string& /* table */) override {
    return;
  }
};


class CalciteServer_ping_args {
 public:

  CalciteServer_ping_args(const CalciteServer_ping_args&) noexcept;
  CalciteServer_ping_args& operator=(const CalciteServer_ping_args&) noexcept;
  CalciteServer_ping_args() noexcept {
  }

  virtual ~CalciteServer_ping_args() noexcept;

  bool operator == (const CalciteServer_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const CalciteServer_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CalciteServer_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_ping_pargs {
 public:


  virtual ~CalciteServer_ping_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_ping_result {
 public:

  CalciteServer_ping_result(const CalciteServer_ping_result&) noexcept;
  CalciteServer_ping_result& operator=(const CalciteServer_ping_result&) noexcept;
  CalciteServer_ping_result() noexcept {
  }

  virtual ~CalciteServer_ping_result() noexcept;

  bool operator == (const CalciteServer_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const CalciteServer_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CalciteServer_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_ping_presult {
 public:


  virtual ~CalciteServer_ping_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class CalciteServer_shutdown_args {
 public:

  CalciteServer_shutdown_args(const CalciteServer_shutdown_args&) noexcept;
  CalciteServer_shutdown_args& operator=(const CalciteServer_shutdown_args&) noexcept;
  CalciteServer_shutdown_args() noexcept {
  }

  virtual ~CalciteServer_shutdown_args() noexcept;

  bool operator == (const CalciteServer_shutdown_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const CalciteServer_shutdown_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CalciteServer_shutdown_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_shutdown_pargs {
 public:


  virtual ~CalciteServer_shutdown_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_shutdown_result {
 public:

  CalciteServer_shutdown_result(const CalciteServer_shutdown_result&) noexcept;
  CalciteServer_shutdown_result& operator=(const CalciteServer_shutdown_result&) noexcept;
  CalciteServer_shutdown_result() noexcept {
  }

  virtual ~CalciteServer_shutdown_result() noexcept;

  bool operator == (const CalciteServer_shutdown_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const CalciteServer_shutdown_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CalciteServer_shutdown_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_shutdown_presult {
 public:


  virtual ~CalciteServer_shutdown_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _CalciteServer_sql2Plan_args__isset {
  _CalciteServer_sql2Plan_args__isset() : query(false), schemaName(false) {}
  bool query :1;
  bool schemaName :1;
} _CalciteServer_sql2Plan_args__isset;

class CalciteServer_sql2Plan_args {
 public:

  CalciteServer_sql2Plan_args(const CalciteServer_sql2Plan_args&);
  CalciteServer_sql2Plan_args& operator=(const CalciteServer_sql2Plan_args&);
  CalciteServer_sql2Plan_args() noexcept
                              : query(),
                                schemaName() {
  }

  virtual ~CalciteServer_sql2Plan_args() noexcept;
  std::string query;
  std::string schemaName;

  _CalciteServer_sql2Plan_args__isset __isset;

  void __set_query(const std::string& val);

  void __set_schemaName(const std::string& val);

  bool operator == (const CalciteServer_sql2Plan_args & rhs) const
  {
    if (!(query == rhs.query))
      return false;
    if (!(schemaName == rhs.schemaName))
      return false;
    return true;
  }
  bool operator != (const CalciteServer_sql2Plan_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CalciteServer_sql2Plan_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_sql2Plan_pargs {
 public:


  virtual ~CalciteServer_sql2Plan_pargs() noexcept;
  const std::string* query;
  const std::string* schemaName;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CalciteServer_sql2Plan_result__isset {
  _CalciteServer_sql2Plan_result__isset() : success(false), parsePlanningErr(false) {}
  bool success :1;
  bool parsePlanningErr :1;
} _CalciteServer_sql2Plan_result__isset;

class CalciteServer_sql2Plan_result {
 public:

  CalciteServer_sql2Plan_result(const CalciteServer_sql2Plan_result&);
  CalciteServer_sql2Plan_result& operator=(const CalciteServer_sql2Plan_result&);
  CalciteServer_sql2Plan_result() noexcept {
  }

  virtual ~CalciteServer_sql2Plan_result() noexcept;
  TPlanResult success;
  ParsePlanningError parsePlanningErr;

  _CalciteServer_sql2Plan_result__isset __isset;

  void __set_success(const TPlanResult& val);

  void __set_parsePlanningErr(const ParsePlanningError& val);

  bool operator == (const CalciteServer_sql2Plan_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(parsePlanningErr == rhs.parsePlanningErr))
      return false;
    return true;
  }
  bool operator != (const CalciteServer_sql2Plan_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CalciteServer_sql2Plan_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _CalciteServer_sql2Plan_presult__isset {
  _CalciteServer_sql2Plan_presult__isset() : success(false), parsePlanningErr(false) {}
  bool success :1;
  bool parsePlanningErr :1;
} _CalciteServer_sql2Plan_presult__isset;

class CalciteServer_sql2Plan_presult {
 public:


  virtual ~CalciteServer_sql2Plan_presult() noexcept;
  TPlanResult* success;
  ParsePlanningError parsePlanningErr;

  _CalciteServer_sql2Plan_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _CalciteServer_updateMetadata_args__isset {
  _CalciteServer_updateMetadata_args__isset() : catalog(false), table(false) {}
  bool catalog :1;
  bool table :1;
} _CalciteServer_updateMetadata_args__isset;

class CalciteServer_updateMetadata_args {
 public:

  CalciteServer_updateMetadata_args(const CalciteServer_updateMetadata_args&);
  CalciteServer_updateMetadata_args& operator=(const CalciteServer_updateMetadata_args&);
  CalciteServer_updateMetadata_args() noexcept
                                    : catalog(),
                                      table() {
  }

  virtual ~CalciteServer_updateMetadata_args() noexcept;
  std::string catalog;
  std::string table;

  _CalciteServer_updateMetadata_args__isset __isset;

  void __set_catalog(const std::string& val);

  void __set_table(const std::string& val);

  bool operator == (const CalciteServer_updateMetadata_args & rhs) const
  {
    if (!(catalog == rhs.catalog))
      return false;
    if (!(table == rhs.table))
      return false;
    return true;
  }
  bool operator != (const CalciteServer_updateMetadata_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CalciteServer_updateMetadata_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_updateMetadata_pargs {
 public:


  virtual ~CalciteServer_updateMetadata_pargs() noexcept;
  const std::string* catalog;
  const std::string* table;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_updateMetadata_result {
 public:

  CalciteServer_updateMetadata_result(const CalciteServer_updateMetadata_result&) noexcept;
  CalciteServer_updateMetadata_result& operator=(const CalciteServer_updateMetadata_result&) noexcept;
  CalciteServer_updateMetadata_result() noexcept {
  }

  virtual ~CalciteServer_updateMetadata_result() noexcept;

  bool operator == (const CalciteServer_updateMetadata_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const CalciteServer_updateMetadata_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CalciteServer_updateMetadata_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class CalciteServer_updateMetadata_presult {
 public:


  virtual ~CalciteServer_updateMetadata_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class CalciteServerClient : virtual public CalciteServerIf {
 public:
  CalciteServerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  CalciteServerClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping() override;
  void send_ping();
  void recv_ping();
  void shutdown() override;
  void send_shutdown();
  void recv_shutdown();
  void sql2Plan(TPlanResult& _return, const std::string& query, const std::string& schemaName) override;
  void send_sql2Plan(const std::string& query, const std::string& schemaName);
  void recv_sql2Plan(TPlanResult& _return);
  void updateMetadata(const std::string& catalog, const std::string& table) override;
  void send_updateMetadata(const std::string& catalog, const std::string& table);
  void recv_updateMetadata();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class CalciteServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<CalciteServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (CalciteServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_shutdown(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_sql2Plan(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_updateMetadata(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  CalciteServerProcessor(::std::shared_ptr<CalciteServerIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &CalciteServerProcessor::process_ping;
    processMap_["shutdown"] = &CalciteServerProcessor::process_shutdown;
    processMap_["sql2Plan"] = &CalciteServerProcessor::process_sql2Plan;
    processMap_["updateMetadata"] = &CalciteServerProcessor::process_updateMetadata;
  }

  virtual ~CalciteServerProcessor() {}
};

class CalciteServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  CalciteServerProcessorFactory(const ::std::shared_ptr< CalciteServerIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< CalciteServerIfFactory > handlerFactory_;
};

class CalciteServerMultiface : virtual public CalciteServerIf {
 public:
  CalciteServerMultiface(std::vector<std::shared_ptr<CalciteServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~CalciteServerMultiface() {}
 protected:
  std::vector<std::shared_ptr<CalciteServerIf> > ifaces_;
  CalciteServerMultiface() {}
  void add(::std::shared_ptr<CalciteServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void shutdown() override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->shutdown();
    }
    ifaces_[i]->shutdown();
  }

  void sql2Plan(TPlanResult& _return, const std::string& query, const std::string& schemaName) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sql2Plan(_return, query, schemaName);
    }
    ifaces_[i]->sql2Plan(_return, query, schemaName);
    return;
  }

  void updateMetadata(const std::string& catalog, const std::string& table) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->updateMetadata(catalog, table);
    }
    ifaces_[i]->updateMetadata(catalog, table);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class CalciteServerConcurrentClient : virtual public CalciteServerIf {
 public:
  CalciteServerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  CalciteServerConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping() override;
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void shutdown() override;
  int32_t send_shutdown();
  void recv_shutdown(const int32_t seqid);
  void sql2Plan(TPlanResult& _return, const std::string& query, const std::string& schemaName) override;
  int32_t send_sql2Plan(const std::string& query, const std::string& schemaName);
  void recv_sql2Plan(TPlanResult& _return, const int32_t seqid);
  void updateMetadata(const std::string& catalog, const std::string& table) override;
  int32_t send_updateMetadata(const std::string& catalog, const std::string& table);
  void recv_updateMetadata(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
