//
// Created by Yifei Yang on 11/11/21.
//

#ifndef FPDB_FPDB_CATALOGUE_INCLUDE_FPDB_CATALOGUE_FORMAT_FORMATTYPE_H
#define FPDB_FPDB_CATALOGUE_INCLUDE_FPDB_CATALOGUE_FORMAT_FORMATTYPE_H

namespace fpdb::catalogue::format {

enum FormatType {
  CSV,
  PARQUET
};

}

#endif //FPDB_FPDB_CATALOGUE_INCLUDE_FPDB_CATALOGUE_FORMAT_FORMATTYPE_H
