//
// Created by Yifei Yang on 1/21/22.
//

#ifndef FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_MESSAGE_MESSAGETYPE_H
#define FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_MESSAGE_MESSAGETYPE_H

namespace fpdb::executor::message {

enum MessageType {
  START,
  STOP,
  CONNECT,
  COMPLETE,
  ERROR,
  SCAN,
  TUPLE,
  TUPLESET_INDEX,
  LOAD_REQUEST,
  LOAD_RESPONSE,
  STORE_REQUEST,
  WEIGHT_REQUEST,
  CACHE_METRICS
};

}

#endif //FPDB_FPDB_EXECUTOR_INCLUDE_FPDB_EXECUTOR_MESSAGE_MESSAGETYPE_H
